### ISSUE TITLE
Activation on staging is inconsistent

### ISSUE THREAD

**Issue by ChucklesTheBeard** [StupidChris/RealChute#49] opened 2015-06-02 01:24 UTC
See: https://www.youtube.com/watch?v=fMvK7LL7Eqo

1st launch goes exactly as expected - chute deploys after staging it properly.
2nd launch also goes as expected, but against documented intended behavior - chute deploys after staging it without moving it out of the bottom stage (it shouldn't activate while on the ground).
3rd launch did not activate the parachute on the initial stage like it did in the 2nd launch.
4th launch did not activate it on staging with the spacebar like the 1st one did.

Sometimes it takes 4+ taps on the spacebar to activate the chute when it's on the final stage.

Although there are other mods in the video, I was able to reproduce the effect with only realchute and module manager installed. I haven't been able to reproduce a third strange behavior, shown here: https://youtu.be/kQOEBC6Sdz8?t=1m8s in which the parachute activates on hitting spacebar, but without the stage advancing.

- Linux hungry 4.0.4-2-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
- KSP v1.0.2.0
- ModuleManager 2.6.5
- RealChute 1.3.2.3

Game log:
https://gist.github.com/ChucklesTheBeard/36806e96bca26ae208b2 (chain of events: load game, load "default" sandbox save, construct a ship extremely similar to the one in the video, launch it, wait for engine to cut out, activate stage, crash into ground because chute didn't deploy, though yes, I do see that it says [parachuteSingle]: Activated)

The craft used in above game log:
https://gist.github.com/ChucklesTheBeard/ed6f3a6ab6d84b0ef055
(the craft used in the video is pretty much identical)

$KSP/GameData/RealChute/Plugins/PluginData/RealChute_Settings.cfg:
https://gist.github.com/ChucklesTheBeard/d39ad14f518811044ad9

~~If there's anything else I can give you, please, let me know, instead of leaving me guessing with "I need tghe same as usual" !~~

**Comment by StupidChris** [comment] 2015-06-03 00:20
Second launch "Documented behaviour"? Where? Which? Parachutes totally can deploy on the ground when staged if the setting forcing the vessel to be going downwards is not on. And for stock chutes it isn't.

Third launch: *also* intended behaviour. Each parachute has a random deployment timer, which is basically a simulation of equipment uncertainty. No two parachute deployment will look alike IRL. It all depends of air flow and how the mortars fire and how well it catches on. For this reason, the parachutes take up to one full second to deploy once the space button is fired. In the previous case, this was long enough that the vessel was already going up, in this launch, it was near instantaneous and the vessel was too slow and still considered to be landed, therefore the deployment did not happen. This is a PEBKAC, don't put your parachutes in your launch stage.

Fourth launch: Too many mods to conculde anything with this video, unable to reproduce locally in any way after 10+ launches. Don't know what you did but you messed something up on your side.

**Comment by ChucklesTheBeard** [comment] 2015-06-03 03:33
Re: 2nd and 3rd launches: My apologies for misunderstanding.

In http://forum.kerbalspaceprogram.com/threads/92229-How-To-Get-Support-%28READ-FIRST%29 form as requested. My sincerest apologies for not knowing you wanted bug reports formatted this way. That was a failure on my part.

---

Re: 4th launch, too many mods to tell - Alright, here we go with a brand new, clean install, following the requested format.

## Troubleshooting: ##
1. Make sure all your addons are up to date.
- ModuleManager 2.6.5, as included in the .zip
- RealChute 1.3.2.3, latest available from the forum thread's OP

2. Make sure you have all your addons installed correctly.
a. Re-installed KSP via steam.
b. Launched game once to let it do whatever it needs to
c. Downloaded Realchute from forum link (v1.3.2.3 according to the zip file name), extracted, copied contents of GameData to $KSP/GameData.

3. Check the stock help sticky and stock known issues sticky.
Nothing related to staging / parachute deployment in
http://forum.kerbalspaceprogram.com/threads/92228-Known-Issues-Self-He10lp

4. On Windows? Use 32bit.
Not on windows - N/A.

5. 32bit KSP? Keep your memory usage low.
Launching as ./KSP.x86_64 - N/A

6. Check to see if the issue was already reported.
It was, back in October, and it was reported as fixed in the changelog for v1.2.6.
Github issue list: possibly related issue #22 - It only mentions MechJeb auto-staging, though.
I've also checked the forum thread from now, back through April 29 - There are no recent reports of this issue.

## Reporting an Issue after you have followed the troubleshooting steps: ##
1. The Logs
Closed out of the game after making the following video, then uploaded these immediately (after substituting "$USER" for my [a-z]{4,10} username).
https://gist.github.com/ChucklesTheBeard/a881ea1c9ec5a0868a7d

2. The Reproduction Steps: The gold standard for reproduction steps is an unedited video of you causing the bug.

This video is unedited save for the key display (key-mon), which was overlayed live to show all relevant inputs. The red flash was a graphical glitch due to resizing KSP while in capture-window mode.
https://youtu.be/kncmpuR03xM
From game launch loading bar, to several deployments. Includes generating the .craft.
The clearest demonstration will most likely be launch 2 (starts at 2:03), in which I wait for it to start descending before advancing the stage. I have to mash space several times before it finally deploys.

3. Clean Environment
I ran rm -rf $KSP before re-downloading with Steam, then only installed RealChute as described in problem shooting step 2. Then I typed up everything in here except "reporting an issue" steps 1. and 2. and started recording the video linked in 2.

**Comment by mongoose11235813** [comment] 2015-07-19 15:11
KSP 1.0.4 I can't reproduce the bug from the second video.
8 launches

**Comment by StupidChris** [comment] 2015-07-24 09:04
Support for RealChute 1.x is dropped, doesn't seem to be a thing in 2.0 test builds, closing.

**Closed by StupidChris** 2015-07-24 09:04 UTC
