### ISSUE TITLE
Chutes do not reliably arm on being staged

### ISSUE THREAD

**Issue by dak180** [StupidChris/RealChute#22] opened 2015-02-05 03:51 UTC
This may only effect stage 0 but when the stage is activated through mechjeb the parachute does not arm; a subsequent manual press of the staging button will are the chute though.

**Comment by StupidChris** [comment] 2015-02-05 04:26
Do you have the "arm on deployment" option active?

**Comment by dak180** [comment] 2015-02-05 04:42
> Do you have the "arm on deployment" option active?

Yes.

**Comment by TedThompson** [comment] 2015-02-05 05:30
Just FYI. I've noticed this too, though in my case I'm using "stage recovery" so it doesn't matter. Stage recovery seems to just check what chutes are present and calculates how much they would retard descent. 

This of course is for boosters typically dropped around 8 to 9 km up so they vanish well before the chutes would actually deploy.  And it's no where near "stage 0".

**Comment by StupidChris** [comment] 2015-02-05 06:30
@dak180 dak180 if you can make this happen without mechjeb deploying the chutes, send me an output_log.txt, other than that, it's probably a mechjeb issue as I can't reproduce it here.

@TedThompson Stage Recovery doesn't actually deploy the parachutes, so the issue is not on my side for sure.

**Comment by TedThompson** [comment] 2015-02-05 07:27
I forgot to mention I too am using mechjeb to fire the stage. I concur however mj must be doing something different then when you hit the space bar.

**Comment by dak180** [comment] 2015-02-05 19:08
http://filebin.net/hnra0smg6t I have not yet been able to reproduce this without mechjeb.

**Comment by StupidChris** [comment] 2015-02-05 19:20
I'll take a look at the relevant MechJeb code and potentially submit a PR if I find faulty code, thanks yall.

**Comment by dak180** [comment] 2015-02-05 19:30
Thank you for looking into it.

**Comment by dak180** [comment] 2015-02-05 20:47
I just managed to get an example where it happened when I manually staged the chute; same url as before.

**Comment by StupidChris** [comment] 2015-02-05 20:58
> ArgumentOutOfRangeException: Argument is out of range.
> Parameter name: index
>   at System.Collections.Generic.List`1[ModuleScienceContainer].get_Item (Int32 index) [0x00000] in > <filename unknown>:0 
>   at ForScience.ForScience.UpdateCurrent () [0x00000] in <filename unknown>:0 
>   at ForScience.ForScience.FixedUpdate () [0x00000] in <filename unknown>:0 

Spammed all over the place during flight. Likely what's causing problem. You also have 89 plugins running on that game, there's too many to pull other conclusive info :/

**Comment by StupidChris** [comment] 2015-02-09 19:28
Had a talk with Sarbian on this, MechJeb does not do any special case handling for RealChute (yet). A new landing planner is being worked on and I believe it'll deal with RealChute. For now better stage them yourself when using MechJeb. I'll close this for now, but if you happen to run into this sans MJ and without mods hoarding the log, feel free to open another issue :)

**Closed by StupidChris** 2015-02-09 19:28 UTC
